### ISSUE TITLE
0.0.5 stopped working

### ISSUE THREAD

**Issue by brendanjerwin** [wdavidw/node-ssh2-connect#1]
Not sure where to debug, maybe you can help guide me.

We were successfully using 0.0.4 with ssh2-exec, but now it seems to just just hang when we call `exec`.

**Comment by brendanjerwin** [comment]
I guess it must have happened here: https://github.com/wdavidw/node-ssh2-connect/commit/72d9c6ede371e76c11dab52a6b544420ecd12a61

**Comment by wdavidw** [comment]
The link you provided prevent the callback to be throw 2 times, a first time when the connection succeed and a second time if it is droped for some reason later (in which case you should listen to the 'error' even from the ssh instance provided inside the callback. not sure this is what you experienced no? it seems like your callback is never called?

**Comment by brendanjerwin** [comment]
yeah, it seems that it never gets beyond connecting.

**Comment by wdavidw** [comment]
did you try commenting the line from the link above, i doubt it will fix anything

**Comment by brendanjerwin** [comment]
Yeah, it didn't change anything. Did I misread the commit log? what else changed? If I use 0.0.4 its fine, 0.0.5 fails my tests.

**Comment by wdavidw** [comment]
i just checked the commit myself, nothing else. didnt ssh2 itself was updated as a sub-dependency, probably?

**Comment by brendanjerwin** [comment]
Ah: https://github.com/wdavidw/node-ssh2-connect/commit/18b011e557b4db5955dad3f2410db041e1d78db3#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L19 bumped the version of ssh2 also.

**Comment by brendanjerwin** [comment]
I'm barking up the wrong tree then.

**Comment by wdavidw** [comment]
ok, make sense. I'm personnaly using those modules intensively, didn't notice any strange behavior

**Comment by brendanjerwin** [comment]
oh, I see ssh2-exec is yours also. Are you using these in concert?

**Comment by wdavidw** [comment]
yes

**Comment by wdavidw** [comment]
i have some minor changes locally, i'll push this now to make sure u got the same than me

**Comment by brendanjerwin** [comment]
could be that the ssh object returned from connect isn't working with exec... 

I get up to: "Creating tmp dir on remote build agent"

``` js
 connect(sshOptions, function(err, ssh) {
        if (err) {
            trace('Failed to connect to remote build agent: %s', err);
            deferred.reject(err);
        } else {
            trace('Creating tmp dir on remote build agent');
            exec({
                cmd: 'mktemp -d /tmp/asset_build.XXXX',
                ssh: ssh
            }, function(err, stdout, stderr) {
                if (err) {
                    trace('Failed to make call: %s', err);
                    deferred.reject(err);
                } else if (stderr) {
                    trace('Call returned stderr: %s', stderr);
                    deferred.reject(stderr);
                } else {
                    var path = stdout.trim();
                    trace('Created tmp dir: %s', path);
                    deferred.resolve(path);
                }
                ssh.end();
            });
        }
    });
```

**Comment by wdavidw** [comment]
i just pushed my ssh2-exec code with version 0.2.8. As i said, i'm using both excessively every day so now that the 2 packages are published, they should work toguether

**Comment by brendanjerwin** [comment]
ok, great. let me try that.

**Comment by wdavidw** [comment]
they also come with tests. to run the test, make sure you can ssh to yourself (`ssh localhost` without a password) and run `npm test`.

**Comment by brendanjerwin** [comment]
hmmm. no. same deal.

The exec call never seems to call its callback if its given an ssh object from the 0.0.5 ssh2-connect.

(my unit tests work against localhost as well, so ssh to local is working.)

**Comment by brendanjerwin** [comment]
BTW, looks like you don't ship the coffee src in the package, so the tests can't run.

**Comment by wdavidw** [comment]
can you look at the test of ssh2-exec and also send me a sample of your code

**Comment by wdavidw** [comment]
yes, you need to `git clone ...` and `npm install`, this is to follow Node.js recommandations

**Comment by brendanjerwin** [comment]
ok, I'll try from the repo. Code sample above. Is that enough do you think?

**Comment by brendanjerwin** [comment]
yep, ssh2-exec tests work on my machine.

**Comment by brendanjerwin** [comment]
The ssh options we are using in the tests:

```
      var options = {
          host      : 'localhost',
          username  : process.env.USER,
          privateKey: fs.readFileSync(path.join(process.env.HOME, '.ssh/id_rsa'), {encoding: 'utf8'})
      };
```

**Comment by wdavidw** [comment]
the latest version of ssh2-exec should fix this. there was a change in an internall ssh2 property that was renamed.

**Comment by brendanjerwin** [comment]
awesome! fixed. Thanks. (and sorry to leave this issue on the wrong project...)
